-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHN9/9SYx35LPJ9D/
dmufqunbXzVkgWoF4GVGgxyTTPegCgYIKoZIzj0DAQehRANCAATD5IiqIpriF65D
zhzI9L1dT6VfdP5oq1bnltVSgr1alqsoMx2yCk/uwMDRNUIg7WxHPJl/6oNGfz7C
VGlfZ+Iw
-----END PRIVATE KEY-----